//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SZ.Aisino.CMS.DbContext.Tax
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using SZ.Aisino.CMS.DbEntity.Tax;
    
    public partial class TaxEntities : DbContext
    {
        public TaxEntities()
            : base("name=TaxEntities")
        {
            this.Configuration.ProxyCreationEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        /// <summary>
        /// 
        /// </summary>
        public DbSet<VIMS_BIZ_INVOICE> VIMS_BIZ_INVOICE { get; set; }
    }
}
